version: "1.0"
stages:
  - "clone"
  - "build"
  - "tag"
  - "push"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "lightstep/terraform-provider-lightstep"
    revision: "${{CF_REVISION}}"
    git: "github"
    stage: "clone"
  build:
    stage: build
    title: Building binary
    type: freestyle
    working_directory: ${{CF_VOLUME_PATH}}/terraform-provider-lightstep
    arguments:
      image: golang:1.16
      commands:
        # - make build
        - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o terraform-provider-lightstep_darwin_v$(cat .go-version)
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o terraform-provider-lightstep_linux_v$(cat .go-version)
        - chmod +x ./terraform-provider-lightstep_darwin_v$(cat .go-version)
        - chmod +x ./terraform-provider-lightstep_linux_v$(cat .go-version)
  setup_github_token:
    stage: tag
    title: Retrieving Github token
    image: codefresh/cli:0.50.1
    commands:
      - echo "GITHUB_TOKEN=`codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password | grep -o '^\S*' | head -1`"  >> ${{CF_VOLUME_PATH}}/env_vars_to_export
  tag_repo:
    stage: tag
    title: Tagging version
    type: freestyle
    working_directory: ${{CF_VOLUME_PATH}}/terraform-provider-lightstep
    arguments:
      image: golang:1.16
      commands:
        - export VERSION=$(cat .go-version)
        - echo $VERSION
        - git tag -f $VERSION ${{CF_REVISION}}
        - git push https://service-codefresh:$GITHUB_TOKEN@github.com/lightstep/terraform-provider-lightstep.git tag $VERSION --force
  get_gcs_key:
    stage: push
    title: Retrieving GCS key
    image: codefresh/cli:0.50.1
    working_directory: ${{CF_VOLUME_PATH}}/terraform-provider-lightstep
    commands:
      - codefresh get contexts codefresh-gcs-service-acct --decrypt -o yaml | yq .spec.data.key -j > sa-key.json
  push_to_gcs:
    stage: push
    title: Pushing to GCS
    type: freestyle
    working_directory: ${{CF_VOLUME_PATH}}/terraform-provider-lightstep
    arguments:
      image: google/cloud-sdk:300.0.0-slim
      commands:
        - gcloud auth activate-service-account --key-file ./sa-key.json
        - export VERSION=$(cat .go-version)
        - gsutil cp terraform-provider-lightstep_* gs://lightstep-terraform-provider/$VERSION/
        - rm ./sa-key.json
